"""add_tenant_id_isolation

Revision ID: b722503cb9aa
Revises: add_users_table_v1
Create Date: 2025-11-24 07:49:21.050078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b722503cb9aa'
down_revision = 'add_users_table_v1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop policy that depends on user_id to allow type alteration
    op.execute('DROP POLICY IF EXISTS "Allow authenticated read own audit_logs" ON audit_logs')

    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('audit_logs', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('resource', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('severity', sa.String(length=20), nullable=True))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='audit_logs')
    op.create_index('idx_audit_tenant_timestamp', 'audit_logs', ['tenant_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_timestamp_event', 'audit_logs', ['timestamp', 'event_type'], unique=False)
    op.create_index('idx_audit_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'action')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.add_column('dlq_permanent_failures', sa.Column('tenant_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_dlq_permanent_failures_tenant_id'), 'dlq_permanent_failures', ['tenant_id'], unique=False)
    op.add_column('lock_audit', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('lock_audit', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('lock_audit', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('lock_audit', sa.Column('tenant_id', sa.String(length=100), nullable=True))
    op.alter_column('lock_audit', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_lock_audit_created_at'), table_name='lock_audit')
    op.drop_index(op.f('idx_lock_audit_lock_key'), table_name='lock_audit')
    op.create_index(op.f('ix_lock_audit_id'), 'lock_audit', ['id'], unique=False)
    op.create_index(op.f('ix_lock_audit_lock_key'), 'lock_audit', ['lock_key'], unique=False)
    op.create_index(op.f('ix_lock_audit_tenant_id'), 'lock_audit', ['tenant_id'], unique=False)
    op.drop_column('lock_audit', 'operation')
    op.drop_column('lock_audit', 'holder_id')
    op.drop_column('lock_audit', 'success')
    op.drop_column('lock_audit', 'ttl_seconds')
    op.drop_column('lock_audit', 'created_at')
    op.drop_constraint(op.f('tenant_user_identifiers_tenant_id_fkey'), 'tenant_user_identifiers', type_='foreignkey')
    op.add_column('tenant_user_identifiers', sa.Column('identifier', sa.String(), nullable=False))
    op.alter_column('tenant_user_identifiers', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tenant_user_identifiers', 'tenant_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='tenant_id::integer')
    op.alter_column('tenant_user_identifiers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_tenant_identifiers_tenant'), table_name='tenant_user_identifiers')
    op.drop_index(op.f('idx_tenant_identifiers_type_value'), table_name='tenant_user_identifiers')
    op.drop_constraint(op.f('tenant_user_identifiers_identifier_type_identifier_value_key'), 'tenant_user_identifiers', type_='unique')
    op.create_index(op.f('ix_tenant_user_identifiers_identifier'), 'tenant_user_identifiers', ['identifier'], unique=False)
    op.create_index(op.f('ix_tenant_user_identifiers_tenant_id'), 'tenant_user_identifiers', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_identifier', 'tenant_user_identifiers', ['identifier'])
    op.create_foreign_key(None, 'tenant_user_identifiers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tenant_user_identifiers', 'updated_at')
    op.drop_column('tenant_user_identifiers', 'identifier_type')
    op.drop_column('tenant_user_identifiers', 'identifier_value')
    op.add_column('tenants', sa.Column('business_hours_start', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('business_hours_end', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('business_hours_timezone', sa.String(), nullable=True))
    op.alter_column('tenants', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('tenants_id_seq'::regclass)"))
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_tenants_status'), table_name='tenants')
    op.drop_index(op.f('idx_tenants_tenant_id'), table_name='tenants')
    
    # Drop dependent FK on users
    op.drop_constraint('fk_users_tenant', 'users', type_='foreignkey')
    
    op.drop_constraint(op.f('tenants_tenant_id_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    
    # Recreate FK on users
    op.create_foreign_key('fk_users_tenant', 'users', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.drop_column('tenants', 'metadata')

    # Re-create policy with cast to text for user_id
    op.execute("CREATE POLICY \"Allow authenticated read own audit_logs\" ON audit_logs FOR SELECT TO authenticated USING (auth.uid()::text = user_id)")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_tenant_id_key'), 'tenants', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_tenants_status'), 'tenants', ['status'], unique=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('tenants', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('tenants_id_seq'::regclass)"))
    op.drop_column('tenants', 'business_hours_timezone')
    op.drop_column('tenants', 'business_hours_end')
    op.drop_column('tenants', 'business_hours_start')
    op.add_column('tenant_user_identifiers', sa.Column('identifier_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tenant_user_identifiers', sa.Column('identifier_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('tenant_user_identifiers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_user_identifiers', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_user_identifiers_tenant_id_fkey'), 'tenant_user_identifiers', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.drop_constraint('uq_identifier', 'tenant_user_identifiers', type_='unique')
    op.drop_index(op.f('ix_tenant_user_identifiers_tenant_id'), table_name='tenant_user_identifiers')
    op.drop_index(op.f('ix_tenant_user_identifiers_identifier'), table_name='tenant_user_identifiers')
    op.create_unique_constraint(op.f('tenant_user_identifiers_identifier_type_identifier_value_key'), 'tenant_user_identifiers', ['identifier_type', 'identifier_value'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tenant_identifiers_type_value'), 'tenant_user_identifiers', ['identifier_type', 'identifier_value'], unique=False)
    op.create_index(op.f('idx_tenant_identifiers_tenant'), 'tenant_user_identifiers', ['tenant_id'], unique=False)
    op.alter_column('tenant_user_identifiers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_user_identifiers', 'tenant_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tenant_user_identifiers', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('tenant_user_identifiers', 'identifier')
    op.add_column('lock_audit', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('lock_audit', sa.Column('ttl_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lock_audit', sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lock_audit', sa.Column('holder_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('lock_audit', sa.Column('operation', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_lock_audit_tenant_id'), table_name='lock_audit')
    op.drop_index(op.f('ix_lock_audit_lock_key'), table_name='lock_audit')
    op.drop_index(op.f('ix_lock_audit_id'), table_name='lock_audit')
    op.create_index(op.f('idx_lock_audit_lock_key'), 'lock_audit', ['lock_key'], unique=False)
    op.create_index(op.f('idx_lock_audit_created_at'), 'lock_audit', ['created_at'], unique=False)
    op.alter_column('lock_audit', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('lock_audit', 'tenant_id')
    op.drop_column('lock_audit', 'details')
    op.drop_column('lock_audit', 'timestamp')
    op.drop_column('lock_audit', 'event_type')
    op.drop_index(op.f('ix_dlq_permanent_failures_tenant_id'), table_name='dlq_permanent_failures')
    op.drop_column('dlq_permanent_failures', 'tenant_id')
    op.add_column('audit_logs', sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index('idx_audit_user_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp_event', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_timestamp', table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('audit_logs', 'severity')
    op.drop_column('audit_logs', 'resource')
    op.drop_column('audit_logs', 'event_type')
    op.drop_column('audit_logs', 'timestamp')
    # ### end Alembic commands ###
