version: 2
updates:
  # Python dependencies (Poetry)
  - package-ecosystem: "pip"
    directory: "/agente-hotel-api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3  # Reducido para evitar spam
    reviewers:
      - "eevans-d"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Guardrails adicionales
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]  # Ignorar major versions automáticamente
    # Solo security y patch updates automáticos
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "direct" 
        update-type: "version-update:semver-patch"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/agente-hotel-api"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
    open-pull-requests-limit: 2  # Reducido - Docker updates menos frecuentes
    reviewers:
      - "eevans-d"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
    open-pull-requests-limit: 2  # Reducido - Actions menos críticos
    reviewers:
      - "eevans-d"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"