"""
Dead Letter Queue (DLQ) Database Models.

Models for persisting permanent failures after max retries exceeded.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import JSON, DateTime, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.lock_audit import Base  # Import Base from existing model


class DLQEntry(Base):
    """Permanent failure entry for messages that exceeded max retries."""

    __tablename__ = "dlq_permanent_failures"

    # Primary key (UUID generated by DLQ service)
    id: Mapped[str] = mapped_column(String(36), primary_key=True)

    # Original message data (serialized UnifiedMessage)
    message_data: Mapped[dict] = mapped_column(JSON, nullable=False)

    # Error information
    error_message: Mapped[str] = mapped_column(Text, nullable=False)
    error_traceback: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    error_type: Mapped[str] = mapped_column(String(255), nullable=False)  # Exception class name

    # Multi-tenancy
    tenant_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)

    # Retry metadata
    retry_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    first_failed_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    last_retry_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Audit timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    def __repr__(self) -> str:
        return (
            f"<DLQEntry(id={self.id}, error_type={self.error_type}, "
            f"retry_count={self.retry_count}, created_at={self.created_at})>"
        )

    def to_dict(self) -> dict:
        """Convert DLQ entry to dictionary for API responses."""
        return {
            "id": self.id,
            "message_data": self.message_data,
            "error_message": self.error_message,
            "error_type": self.error_type,
            "retry_count": self.retry_count,
            "first_failed_at": self.first_failed_at.isoformat() if self.first_failed_at else None,
            "last_retry_at": self.last_retry_at.isoformat() if self.last_retry_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
