# [PROMPT 3.3] docker-compose.production.yml

version: "3.8"

services:
  qloapps:
    image: webkul/qloapps:latest
    # ... (configuración similar a docker-compose.yml pero para prod)

  mysql:
    image: mysql:8.0
    # ...

  agente-api:
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file: .env.production
    # ...

  postgres:
    image: postgres:15-alpine
    # ...

  redis:
    image: redis:7-alpine
    # ...

  nginx:
    image: nginx:alpine
    ports: ["80:80", "443:443"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - certbot_data:/var/www/certbot:ro
      - ./nginx/ssl:/etc/letsencrypt
    # ...

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot_data:
  # ... otros volúmenes
