# Fly.io configuration for agente-hotel-api
app = "agente-hotel-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile.optimized"
  [build.args]
    INCLUDE_AUDIO = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

[checks]
  [checks.live]
    type = "http"
    grace_period = "10s"
    interval = "15s"
    method = "get"
    path = "/health/live"
    port = 8000
    timeout = "5s"
  [checks.ready]
    type = "http"
    grace_period = "15s"
    interval = "20s"
    method = "get"
    path = "/health/ready"
    port = 8000
    timeout = "5s"
