# [PROMPT 2.5 + E.3] rasa_nlu/config.yml
# Rasa NLU Configuration - Production-Ready Spanish Hotel Bot
# DIET Classifier with optimized pipeline for 15+ intents

recipe: default.v1

language: es

pipeline:
  # ==================== TOKENIZATION ====================
  - name: WhitespaceTokenizer
    # Spanish tokenizer (spaces, punctuation)
  
  # ==================== FEATURIZERS ====================
  - name: RegexFeaturizer
    # Pattern-based features (dates, numbers, emails)
  
  - name: LexicalSyntacticFeaturizer
    # POS tagging features for Spanish
  
  - name: CountVectorsFeaturizer
    # Word-level bag-of-words
    analyzer: word
    min_ngram: 1
    max_ngram: 2
  
  - name: CountVectorsFeaturizer
    # Character-level n-grams (handles typos, informal Spanish)
    analyzer: char_wb
    min_ngram: 2
    max_ngram: 5
  
  # ==================== INTENT CLASSIFICATION + ENTITY EXTRACTION ====================
  - name: DIETClassifier
    # Dual Intent Entity Transformer
    epochs: 100
    constrain_similarities: true
    # Model architecture
    model_confidence: softmax
    # Regularization
    drop_rate: 0.2
    # Training
    batch_size: 
      - 64
      - 256
    learning_rate: 0.001
    # Early stopping
    evaluate_every_number_of_epochs: 20
    evaluate_on_number_of_examples: 50
  
  - name: EntitySynonymMapper
    # Maps synonyms (doble -> habitación doble)
  
  - name: ResponseSelector
    # Response selection for fallback/chitchat
    epochs: 100
    constrain_similarities: true
    retrieval_intent: out_of_scope

# ==================== POLICIES (for dialogue management) ====================
policies:
  - name: MemoizationPolicy
    max_history: 5
  
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
  
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    # Confidence thresholds
    # - intent: >0.75 → confident
    # - intent: 0.40-0.75 → uncertain (ask clarification)
    # - intent: <0.40 → fallback
