#!/bin/sh
set -eu

# Use a writable path inside the container
CFG="/tmp/generated.yml"

# Detect receivers from env
HAS_SLACK=0
if [ -n "${SLACK_WEBHOOK_URL:-}" ]; then
  HAS_SLACK=1
fi

HAS_EMAIL=0
if [ -n "${ALERT_EMAIL_TO:-}" ] && [ -n "${SMTP_HOST:-}" ] && [ -n "${SMTP_PORT:-}" ] && [ -n "${SMTP_USER:-}" ] && [ -n "${SMTP_PASSWORD:-}" ]; then
  HAS_EMAIL=1
fi

SLACK_CHANNEL="${SLACK_CHANNEL:-#alertas-agente}"
EMAIL_FROM="${ALERT_EMAIL_FROM:-alerts@example.com}"

# Base config
cat > "$CFG" <<EOF
# generated by entrypoint.sh
global:
  resolve_timeout: 5m

route:
  receiver: "null"
EOF

# Conditional routes
if [ "$HAS_SLACK" -eq 1 ] || [ "$HAS_EMAIL" -eq 1 ]; then
  cat >> "$CFG" <<'EOF'
  routes:
EOF
fi

if [ "$HAS_SLACK" -eq 1 ]; then
  cat >> "$CFG" <<'EOF'
    - matchers:
        - severity = critical
      receiver: slack
EOF
fi

if [ "$HAS_EMAIL" -eq 1 ]; then
  cat >> "$CFG" <<'EOF'
    - matchers:
        - severity = warning
      receiver: email
EOF
fi

# Receivers section
cat >> "$CFG" <<'EOF'
receivers:
  - name: "null"
EOF

if [ "$HAS_SLACK" -eq 1 ]; then
  cat >> "$CFG" <<EOF
  - name: slack
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: "${SLACK_CHANNEL}"
        send_resolved: true
        title: "[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}"
        text: >-
          {{ range .Alerts }}• {{ .Annotations.summary }}
          {{ .Annotations.description }}
          {{ end }}
EOF
fi

if [ "$HAS_EMAIL" -eq 1 ]; then
  cat >> "$CFG" <<EOF
  - name: email
    email_configs:
      - to: ${ALERT_EMAIL_TO}
        from: ${EMAIL_FROM}
        smarthost: ${SMTP_HOST}:${SMTP_PORT}
        auth_username: ${SMTP_USER}
        auth_password: ${SMTP_PASSWORD}
        require_tls: true
EOF
fi

echo "Using generated Alertmanager config:" >&2
echo "-----------------------------------" >&2
cat "$CFG" >&2
echo "-----------------------------------" >&2

exec /bin/alertmanager \
  --config.file="$CFG" \
  --storage.path=/tmp/alertmanager \
  --log.level=info
