#!/bin/sh
set -eu

CFG="/etc/alertmanager/generated.yml"

# Detect receivers from env
HAS_SLACK=0
if [ -n "${SLACK_WEBHOOK_URL:-}" ]; then
  HAS_SLACK=1
fi

HAS_EMAIL=0
if [ -n "${ALERT_EMAIL_TO:-}" ] && [ -n "${SMTP_HOST:-}" ] && [ -n "${SMTP_PORT:-}" ] && [ -n "${SMTP_USER:-}" ] && [ -n "${SMTP_PASSWORD:-}" ]; then
  HAS_EMAIL=1
fi

# Build routes and receivers blocks
ROUTES=""
RECEIVERS=""

if [ "$HAS_SLACK" -eq 1 ] || [ "$HAS_EMAIL" -eq 1 ]; then
  ROUTES="  routes:\n"
fi

if [ "$HAS_SLACK" -eq 1 ]; then
  ROUTES="$ROUTES    - matchers:\n        - severity = critical\n      receiver: slack\n"
  SLACK_CHANNEL="${SLACK_CHANNEL:-#alertas-agente}"
  RECEIVERS="$RECEIVERS  - name: slack\n    slack_configs:\n      - api_url: ${SLACK_WEBHOOK_URL}\n        channel: \"${SLACK_CHANNEL}\"\n        send_resolved: true\n        title: \"[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}\"\n        text: >-\n          {{ range .Alerts }}• {{ .Annotations.summary }}\\n{{ .Annotations.description }}\\n{{ end }}\n"
fi

if [ "$HAS_EMAIL" -eq 1 ]; then
  ROUTES="$ROUTES    - matchers:\n        - severity = warning\n      receiver: email\n"
  EMAIL_FROM="${ALERT_EMAIL_FROM:-alerts@example.com}"
  RECEIVERS="$RECEIVERS  - name: email\n    email_configs:\n      - to: ${ALERT_EMAIL_TO}\n        from: ${EMAIL_FROM}\n        smarthost: ${SMTP_HOST}:${SMTP_PORT}\n        auth_username: ${SMTP_USER}\n        auth_password: ${SMTP_PASSWORD}\n        require_tls: true\n"
fi

cat > "$CFG" <<EOF
# generated by entrypoint.sh
global:
  resolve_timeout: 5m

route:
  receiver: "null"
${ROUTES}

receivers:
  - name: "null"
${RECEIVERS}
EOF

echo "Using generated Alertmanager config:" >&2
echo "-----------------------------------" >&2
cat "$CFG" >&2
echo "-----------------------------------" >&2

exec /bin/alertmanager \
  --config.file="$CFG" \
  --storage.path=/alertmanager \
  --log.level=info
