groups:
  - name: agente-test
    interval: 15s
    rules:
      - alert: AlwaysFiring
        expr: vector(1)
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Alerta de prueba (AlwaysFiring)"
          description: "Alerta sintética para validar receivers y ruteo."
