name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r agente-hotel-api/requirements-test.txt

      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff format --check agente-hotel-api
          ruff check agente-hotel-api

      - name: Run unit tests (pytest)
        working-directory: agente-hotel-api
        run: |
          pytest -q tests