name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint-test-security:
    name: Lint + Tests + Security Fast
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install base tooling
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install ruff gitleaks

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Install project deps (poetry)
        working-directory: agente-hotel-api
        run: |
          poetry install --all-extras --no-root

      - name: Lint & static analysis
        working-directory: agente-hotel-api
        run: |
          make lint

      - name: Run tests
        working-directory: agente-hotel-api
        run: make test

      - name: Security Fast Scan
        working-directory: agente-hotel-api
        run: make security-fast || true

      - name: Build Docker image
        working-directory: agente-hotel-api
        run: docker build -t agente-hotel-api:ci .

      - name: Scan Docker image vulnerabilities
        working-directory: agente-hotel-api
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 agente-hotel-api:ci || {
            echo "::warning::High/Critical vulnerabilities found in Docker image"
            exit 0
          }

  build-only:
    name: Build Only (post quality gates)
    runs-on: ubuntu-latest
    needs: [lint-test-security]
    steps:
      - uses: actions/checkout@v4
      - name: Docker build
        working-directory: agente-hotel-api
        run: docker build -t agente-hotel-api:ci .